# Generated by Django 5.0.6 on 2024-06-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_num', models.PositiveSmallIntegerField()),
                ('teacher_in_charge', models.CharField(max_length=15)),
                ('number_of_students', models.PositiveSmallIntegerField()),
                ('number_of_books', models.PositiveSmallIntegerField()),
                ('number_of_boards', models.PositiveSmallIntegerField()),
                ('class_color', models.CharField(max_length=10)),
                ('number_of_windows', models.PositiveSmallIntegerField()),
                ('common_tribe', models.CharField(max_length=12)),
                ('number_of_arts', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
